version: '3.1'
services:
  db:
    build: .
    container_name: artofpostgres
    security_opt:
      - seccomp:unconfined
    environment:
      HOST_IP: host.docker.internal
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5440:5432
    restart: always
    volumes:
      - .:/var/lib/postgresql
